FROM docker:dind

RUN apk add --no-cache \
    curl \
    bash \
    ca-certificates \
    gzip

# Install kubectl directly from Kubernetes release binaries and helm chart
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm -f kubectl && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh && mkdir -p /etc/docker
COPY daemon.json /etc/docker/daemon.json


