#Create service account for jenkins
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
---

#Create non expiration token for jenkins service account to authenticate the application pods
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: jenkins-token-secret
  annotations:
    kubernetes.io/service-account.name: "jenkins"
  namespace: jenkins
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-permissions
rules:
- apiGroups: ["apps"]
#include resources like [Deployments, DaemonSets, StatefulSets, ReplicaSets, ControllerRevisions]:
  resources: ["*"] 
  verbs: ["create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: jenkins-permissions-binding
subjects:
- kind: ServiceAccount
  name: jenkins
  apiGroup: ""
  namespace: jenkins
roleRef:
  kind: ClusterRole
  name: jenkins-permissions
  apiGroup: rbac.authorization.k8s.io
